/**
 * 国家列表 — 含 CDN 国旗图片
 * 按英文首字母 A-Z 排序（覆盖 150+ 国家/地区）
 *
 * @package Soeteck\Astro
 */

export interface Country {
  code: string;   // ISO 3166-1 alpha-2 (lowercase for flag CDN)
  flag: string;   // Emoji flag
  flagUrl: string; // CDN flag image URL
  name: string;   // English name
}

function flagUrl(code: string): string {
  return `https://flagcdn.com/24x18/${code.toLowerCase()}.png`;
}

function c(code: string, name: string): Country {
  const emojiFlags: Record<string, string> = {
    AE: '🇦🇪', AF: '🇦🇫', AL: '🇦🇱', AM: '🇦🇲', AO: '🇦🇴', AR: '🇦🇷', AT: '🇦🇹',
    AU: '🇦🇺', AZ: '🇦🇿', BA: '🇧🇦', BD: '🇧🇩', BE: '🇧🇪', BF: '🇧🇫', BG: '🇧🇬',
    BH: '🇧🇭', BI: '🇧🇮', BJ: '🇧🇯', BN: '🇧🇳', BO: '🇧🇴', BR: '🇧🇷', BS: '🇧🇸',
    BT: '🇧🇹', BW: '🇧🇼', BY: '🇧🇾', BZ: '🇧🇿',
    CA: '🇨🇦', CD: '🇨🇩', CF: '🇨🇫', CG: '🇨🇬', CH: '🇨🇭', CI: '🇨🇮', CL: '🇨🇱',
    CM: '🇨🇲', CN: '🇨🇳', CO: '🇨🇴', CR: '🇨🇷', CU: '🇨🇺', CV: '🇨🇻', CY: '🇨🇾',
    CZ: '🇨🇿',
    DE: '🇩🇪', DJ: '🇩🇯', DK: '🇩🇰', DO: '🇩🇴', DZ: '🇩🇿',
    EC: '🇪🇨', EE: '🇪🇪', EG: '🇪🇬', ER: '🇪🇷', ES: '🇪🇸', ET: '🇪🇹',
    FI: '🇫🇮', FJ: '🇫🇯', FR: '🇫🇷',
    GA: '🇬🇦', GB: '🇬🇧', GE: '🇬🇪', GH: '🇬🇭', GM: '🇬🇲', GN: '🇬🇳', GQ: '🇬🇶',
    GR: '🇬🇷', GT: '🇬🇹', GW: '🇬🇼', GY: '🇬🇾',
    HK: '🇭🇰', HN: '🇭🇳', HR: '🇭🇷', HT: '🇭🇹', HU: '🇭🇺',
    ID: '🇮🇩', IE: '🇮🇪', IL: '🇮🇱', IN: '🇮🇳', IQ: '🇮🇶', IR: '🇮🇷', IS: '🇮🇸',
    IT: '🇮🇹',
    JM: '🇯🇲', JO: '🇯🇴', JP: '🇯🇵',
    KE: '🇰🇪', KG: '🇰🇬', KH: '🇰🇭', KI: '🇰🇮', KM: '🇰🇲', KN: '🇰🇳', KP: '🇰🇵',
    KR: '🇰🇷', KW: '🇰🇼', KZ: '🇰🇿',
    LA: '🇱🇦', LB: '🇱🇧', LC: '🇱🇨', LI: '🇱🇮', LK: '🇱🇰', LR: '🇱🇷', LS: '🇱🇸',
    LT: '🇱🇹', LU: '🇱🇺', LV: '🇱🇻', LY: '🇱🇾',
    MA: '🇲🇦', MC: '🇲🇨', MD: '🇲🇩', ME: '🇲🇪', MG: '🇲🇬', MK: '🇲🇰', ML: '🇲🇱',
    MM: '🇲🇲', MN: '🇲🇳', MO: '🇲🇴', MR: '🇲🇷', MT: '🇲🇹', MU: '🇲🇺', MV: '🇲🇻',
    MW: '🇲🇼', MX: '🇲🇽', MY: '🇲🇾', MZ: '🇲🇿',
    NA: '🇳🇦', NE: '🇳🇪', NG: '🇳🇬', NI: '🇳🇮', NL: '🇳🇱', NO: '🇳🇴', NP: '🇳🇵',
    NZ: '🇳🇿',
    OM: '🇴🇲',
    PA: '🇵🇦', PE: '🇵🇪', PG: '🇵🇬', PH: '🇵🇭', PK: '🇵🇰', PL: '🇵🇱', PS: '🇵🇸',
    PT: '🇵🇹', PY: '🇵🇾',
    QA: '🇶🇦',
    RO: '🇷🇴', RS: '🇷🇸', RU: '🇷🇺', RW: '🇷🇼',
    SA: '🇸🇦', SB: '🇸🇧', SC: '🇸🇨', SD: '🇸🇩', SE: '🇸🇪', SG: '🇸🇬', SI: '🇸🇮',
    SK: '🇸🇰', SL: '🇸🇱', SM: '🇸🇲', SN: '🇸🇳', SO: '🇸🇴', SR: '🇸🇷', SS: '🇸🇸',
    ST: '🇸🇹', SV: '🇸🇻', SY: '🇸🇾', SZ: '🇸🇿',
    TD: '🇹🇩', TG: '🇹🇬', TH: '🇹🇭', TJ: '🇹🇯', TL: '🇹🇱', TM: '🇹🇲', TN: '🇹🇳',
    TR: '🇹🇷', TT: '🇹🇹', TW: '🇹🇼', TZ: '🇹🇿',
    UA: '🇺🇦', UG: '🇺🇬', US: '🇺🇸', UY: '🇺🇾', UZ: '🇺🇿',
    VA: '🇻🇦', VC: '🇻🇨', VE: '🇻🇪', VN: '🇻🇳', VU: '🇻🇺',
    YE: '🇾🇪',
    ZA: '🇿🇦', ZM: '🇿🇲', ZW: '🇿🇼',
  };
  return {
    code,
    flag: emojiFlags[code] || '',
    flagUrl: flagUrl(code),
    name,
  };
}

export const COUNTRIES: Country[] = [
  c('AF', 'Afghanistan'),
  c('AL', 'Albania'),
  c('DZ', 'Algeria'),
  c('AO', 'Angola'),
  c('AR', 'Argentina'),
  c('AM', 'Armenia'),
  c('AU', 'Australia'),
  c('AT', 'Austria'),
  c('AZ', 'Azerbaijan'),
  c('BH', 'Bahrain'),
  c('BD', 'Bangladesh'),
  c('BY', 'Belarus'),
  c('BE', 'Belgium'),
  c('BZ', 'Belize'),
  c('BJ', 'Benin'),
  c('BT', 'Bhutan'),
  c('BO', 'Bolivia'),
  c('BA', 'Bosnia and Herzegovina'),
  c('BW', 'Botswana'),
  c('BR', 'Brazil'),
  c('BN', 'Brunei'),
  c('BG', 'Bulgaria'),
  c('BF', 'Burkina Faso'),
  c('BI', 'Burundi'),
  c('KH', 'Cambodia'),
  c('CM', 'Cameroon'),
  c('CA', 'Canada'),
  c('CV', 'Cape Verde'),
  c('CF', 'Central African Republic'),
  c('TD', 'Chad'),
  c('CL', 'Chile'),
  c('CN', 'China'),
  c('CO', 'Colombia'),
  c('KM', 'Comoros'),
  c('CG', 'Congo'),
  c('CD', 'Congo (DRC)'),
  c('CR', 'Costa Rica'),
  c('CI', "Côte d'Ivoire"),
  c('HR', 'Croatia'),
  c('CU', 'Cuba'),
  c('CY', 'Cyprus'),
  c('CZ', 'Czech Republic'),
  c('DK', 'Denmark'),
  c('DJ', 'Djibouti'),
  c('DO', 'Dominican Republic'),
  c('EC', 'Ecuador'),
  c('EG', 'Egypt'),
  c('SV', 'El Salvador'),
  c('GQ', 'Equatorial Guinea'),
  c('ER', 'Eritrea'),
  c('EE', 'Estonia'),
  c('SZ', 'Eswatini'),
  c('ET', 'Ethiopia'),
  c('FJ', 'Fiji'),
  c('FI', 'Finland'),
  c('FR', 'France'),
  c('GA', 'Gabon'),
  c('GM', 'Gambia'),
  c('GE', 'Georgia'),
  c('DE', 'Germany'),
  c('GH', 'Ghana'),
  c('GR', 'Greece'),
  c('GT', 'Guatemala'),
  c('GN', 'Guinea'),
  c('GW', 'Guinea-Bissau'),
  c('GY', 'Guyana'),
  c('HT', 'Haiti'),
  c('HN', 'Honduras'),
  c('HK', 'Hong Kong, China'),
  c('HU', 'Hungary'),
  c('IS', 'Iceland'),
  c('IN', 'India'),
  c('ID', 'Indonesia'),
  c('IR', 'Iran'),
  c('IQ', 'Iraq'),
  c('IE', 'Ireland'),
  c('IL', 'Israel'),
  c('IT', 'Italy'),
  c('JM', 'Jamaica'),
  c('JP', 'Japan'),
  c('JO', 'Jordan'),
  c('KZ', 'Kazakhstan'),
  c('KE', 'Kenya'),
  c('KI', 'Kiribati'),
  c('KW', 'Kuwait'),
  c('KG', 'Kyrgyzstan'),
  c('LA', 'Laos'),
  c('LV', 'Latvia'),
  c('LB', 'Lebanon'),
  c('LS', 'Lesotho'),
  c('LR', 'Liberia'),
  c('LY', 'Libya'),
  c('LI', 'Liechtenstein'),
  c('LT', 'Lithuania'),
  c('LU', 'Luxembourg'),
  c('MO', 'Macau, China'),
  c('MG', 'Madagascar'),
  c('MW', 'Malawi'),
  c('MY', 'Malaysia'),
  c('MV', 'Maldives'),
  c('ML', 'Mali'),
  c('MT', 'Malta'),
  c('MR', 'Mauritania'),
  c('MU', 'Mauritius'),
  c('MX', 'Mexico'),
  c('FM', 'Micronesia'),
  c('MD', 'Moldova'),
  c('MC', 'Monaco'),
  c('MN', 'Mongolia'),
  c('ME', 'Montenegro'),
  c('MA', 'Morocco'),
  c('MZ', 'Mozambique'),
  c('MM', 'Myanmar'),
  c('NA', 'Namibia'),
  c('NP', 'Nepal'),
  c('NL', 'Netherlands'),
  c('NZ', 'New Zealand'),
  c('NI', 'Nicaragua'),
  c('NE', 'Niger'),
  c('NG', 'Nigeria'),
  c('KP', 'North Korea'),
  c('MK', 'North Macedonia'),
  c('NO', 'Norway'),
  c('OM', 'Oman'),
  c('PK', 'Pakistan'),
  c('PW', 'Palau'),
  c('PS', 'Palestine'),
  c('PA', 'Panama'),
  c('PG', 'Papua New Guinea'),
  c('PY', 'Paraguay'),
  c('PE', 'Peru'),
  c('PH', 'Philippines'),
  c('PL', 'Poland'),
  c('PT', 'Portugal'),
  c('QA', 'Qatar'),
  c('RO', 'Romania'),
  c('RU', 'Russia'),
  c('RW', 'Rwanda'),
  c('KN', 'Saint Kitts and Nevis'),
  c('LC', 'Saint Lucia'),
  c('VC', 'Saint Vincent and the Grenadines'),
  c('SM', 'San Marino'),
  c('ST', 'São Tomé and Príncipe'),
  c('SA', 'Saudi Arabia'),
  c('SN', 'Senegal'),
  c('RS', 'Serbia'),
  c('SC', 'Seychelles'),
  c('SL', 'Sierra Leone'),
  c('SG', 'Singapore'),
  c('SK', 'Slovakia'),
  c('SI', 'Slovenia'),
  c('SB', 'Solomon Islands'),
  c('SO', 'Somalia'),
  c('ZA', 'South Africa'),
  c('KR', 'South Korea'),
  c('SS', 'South Sudan'),
  c('ES', 'Spain'),
  c('LK', 'Sri Lanka'),
  c('SD', 'Sudan'),
  c('SR', 'Suriname'),
  c('SE', 'Sweden'),
  c('CH', 'Switzerland'),
  c('SY', 'Syria'),
  c('TW', 'Taiwan, China'),
  c('TJ', 'Tajikistan'),
  c('TZ', 'Tanzania'),
  c('TH', 'Thailand'),
  c('TL', 'Timor-Leste'),
  c('TG', 'Togo'),
  c('TT', 'Trinidad and Tobago'),
  c('TN', 'Tunisia'),
  c('TR', 'Turkey'),
  c('TM', 'Turkmenistan'),
  c('UG', 'Uganda'),
  c('UA', 'Ukraine'),
  c('AE', 'United Arab Emirates'),
  c('GB', 'United Kingdom'),
  c('US', 'United States'),
  c('UY', 'Uruguay'),
  c('UZ', 'Uzbekistan'),
  c('VU', 'Vanuatu'),
  c('VA', 'Vatican City'),
  c('VE', 'Venezuela'),
  c('VN', 'Vietnam'),
  c('YE', 'Yemen'),
  c('ZM', 'Zambia'),
  c('ZW', 'Zimbabwe'),
];

